### ISSUE TITLE
can support Arrow OS?

### ISSUE THREAD

**Issue by soralis0912** [GoogleChinaCEO/device_xiaomi_chopin#5]
can you add support arrow os ?

if possible merge this branch

https://github.com/Xiaomi-chopin-Development/device_xiaomi_chopin/tree/arrow-11.0

**Comment by Yuyuko1024** [comment]
I think you can use these changes yourself, I don't really want to add it to my device tree (unless I need it) XD

**Comment by soralis0912** [comment]
@Yuyuko1024 ok thanks
